name: Run Tests

on:
  pull_request:
    types: [labeled]

jobs:
  tests:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'run-tests' ) }}
    runs-on:
      - ubuntu-20.04
    env:
      ERIGON_TAG: latest
      
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: Run tests
        id: api_tests
        run: make automated-testing

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./docker/report/result.xml
          check_name: "Test Results (dev)"
